export const AlleVeranstaltungen = [{
    id: '1',    
    name: 'Heidenheimer Weihnachtsmarkt',
    datum: '02.02.2022',
    ort: 'Brunnenplatz',
    preis: '0,00',
    beschreibung: 'TEST TEST test test',
    genehmigung: true,
    Zeitstempel: "2023-12-04T12:36:56.908Z"
}, {
    id: '2',
    name: 'Felix Rave',
    datum: '01.01.2025',
    ort: 'Rummel',
    preis: '24,00',
    beschreibung: 'TEST TEST test test',
    genehmigung: true,
    Zeitstempel: "2023-12-05T12:36:56.908Z"
}, {
    id: '3',
    name: 'Reinorgeln',
    datum: '02.02.2022',
    ort: 'Simons Haus',
    preis: '0,00',
    beschreibung: 'TEST TEST test test',
    genehmigung: false,
}, {
    id: '4',
    name: 'Jannis Party',
    datum: '01.01.2024',
    ort: 'Jannis Haus',
    preis: '45,00',
    beschreibung: 'TEST TEST test test',
    genehmigung: false,
}, {
    id: '5',
    name: 'Fete von Kai',
    datum: '09.09.1999',
    ort: 'Kais Haus',
    preis: '999,00',
    beschreibung: 'TEST TEST test test',
    genehmigung: true,
}, {
    id: '6',
    name: 'Keine Feier ohne Meyer',
    datum: '02.02.2022',
    ort: 'Wiesbaden',
    preis: '0,00',
    beschreibung: 'TEST TEST test test',
    genehmigung: false,
}, {
    id: '7',
    name: 'Dicke Party',
    datum: '25.04.2026',
    ort: 'München',
    preis: '82,00',
    beschreibung: 'TEST TEST test test',
    genehmigung: false,
    Zeitstempel: "2023-12-06T12:36:56.908Z"
}];